### ISSUE TITLE
Add abort logic

### ISSUE THREAD

**Issue by AkashBhave** [ProjectCaelus/flight-software#10]
Figure out what processes to stop and what commands to run on the valves.

**Comment by catalanoanna00** [comment]
processes: hard abort (cannot be interrupted), soft abort (can be interrupted), close valve (for a certain number of degrees, put in through a parameter) open valve (opens the valve for a certain number of degrees, put in through parameter)
methods: check_valve (check if the valve is open or not), close_valve (close the valve), open_valve (opens the valve), hard_abort (opens the vent and drains valves), soft_abort (same as previous but can be interrupted), send_data (important values we need when aborting), tank_vent

**Comment by catalanoanna00** [comment]
not sure how to check if the valve is closed or not
