### ISSUE TITLE
Create force sensor

### ISSUE THREAD

**Issue by AkashBhave** [ProjectCaelus/flight-software#12]
- [ ] Determine how to interface with the sensor (believe it's I2C)
- [ ] Create a struct that implements the `SensorTrait` trait
- [ ] Use actual data that the device returns, report to _supervisor_

Consult the IMU struct for reference.

**Comment by catalanoanna00** [comment]
Load cell using an amplifier called hx711
Also instead of SensorTrait, should I use SensorType?
