### ISSUE TITLE
Add valve control functionality

### ISSUE THREAD

**Issue by AkashBhave** [ProjectCaelus/flight-software#5]
# Tasks
- [ ] Create _/modules/valve_ folder
- [ ] Create `Valve` struct

# Functions
  - `actuate(position, speed)`: speed is optional, defaults to max speed
  - `position()`: get position of valve
  - `is_actuating() -> bool`: returns state of internal lock

# Variables
- position: `i8`
- lock: `Mutex`

**Comment by stephen-huan** [comment]
done in Python
